from enum import Enum


class ErrorResponse(str, Enum):
    INVALID_EMAIL = 'INVALID_EMAIL'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    INVALID_TOKEN = 'INVALID_TOKEN'
    USER_ALREADY_EXIST = 'USER_ALREADY_EXIST'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    INTERNAL_ERR0R = 'INTERNAL_ERR0R'
