from enum import Enum

STATUS_OK = 'OK'


class ErrorResponse(str, Enum):
    INVALID_EMAIL = 'INVALID_EMAIL'
    EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    INVALID_TOKEN = 'INVALID_TOKEN'
    USER_ALREADY_EXIST = 'USER_ALREADY_EXIST'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    INTERNAL_ERR0R = 'INTERNAL_ERR0R'

    CREATING_NOTE_CATEGORY_ERROR = 'CREATING_NOTE_CATEGORY_ERROR'
    UPDATING_NOTE_CATEGORY_ERROR = 'UPDATING_NOTE_CATEGORY_ERROR'
    DELETING_NOTE_CATEGORY_ERROR = 'DELETING_NOTE_CATEGORY_ERROR'
