"""expire

Revision ID: 0327b6cd7fb1
Revises: 071768f31d12
Create Date: 2024-01-17 21:51:07.966951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0327b6cd7fb1'
down_revision: Union[str, None] = '071768f31d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_token', sa.Column('expire', sa.String(), nullable=False))
    op.drop_column('auth_token', 'expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_token', sa.Column('expired', sa.VARCHAR(), nullable=False))
    op.drop_column('auth_token', 'expire')
    # ### end Alembic commands ###
