"""update notes 25.01

Revision ID: 70b9290bba11
Revises: 8a1c77d6cc43
Create Date: 2024-01-25 20:50:44.927858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b9290bba11'
down_revision: Union[str, None] = '8a1c77d6cc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
