"""postgres migration

Revision ID: 75ad2502602b
Revises: 921e05345d67
Create Date: 2024-01-20 19:43:23.883990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ad2502602b'
down_revision: Union[str, None] = '921e05345d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'notes', 'notes_categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.alter_column('notes', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
